processors:
  - ["stylelint-processor-styled-components", {
    "moduleName": "styled-components",
    "importName": "default",
    "strict": false,
    "ignoreFiles": [],
    "parserPlugins": [
      "jsx",
      "objectRestSpread",
      ["decorators", { "decoratorsBeforeExport": true }],
      "classProperties",
      "exportExtensions",
      "asyncGenerators",
      "functionBind",
      "functionSent",
      "dynamicImport",
      "optionalCatchBinding",
      "optionalChaining",
      "nullishCoalescingOperator",
    ]
  }]
extends:
  - "stylelint-config-recommended"
  - "stylelint-config-styled-components"

rules:
  at-rule-no-vendor-prefix: true
  block-no-empty: true
  color-hex-case: 'lower'
  color-hex-length: 'long'
  color-named: 'never'
  color-no-invalid-hex: true
  comment-no-empty: true
  declaration-bang-space-before: 'always'
  declaration-block-no-duplicate-properties: true
  declaration-block-single-line-max-declarations: 1
  declaration-colon-space-after: 'always-single-line'
  declaration-colon-space-before: 'never'
  font-family-no-duplicate-names: true
  font-weight-notation: 'numeric'
  function-comma-space-after: 'always-single-line'
  function-max-empty-lines: 0
  function-name-case: 'lower'
  function-url-quotes: 'always'
  function-whitespace-after: 'always'
  length-zero-no-unit: true
  linebreaks: 'unix'
  max-empty-lines: 2
  max-line-length: 100
  media-feature-name-no-vendor-prefix: true
  no-empty-first-line: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-unknown-animations: true
  property-no-unknown: true
  property-no-vendor-prefix: true
  selector-list-comma-space-after: 'always-single-line'
  selector-list-comma-space-before: 'never'
  selector-max-empty-lines: 1
  selector-no-vendor-prefix: true
  selector-pseudo-element-case: 'lower'
  selector-pseudo-element-colon-notation: 'double'
  shorthand-property-no-redundant-values: true
  string-quotes: 'single'
  unit-no-unknown: true
  value-list-comma-newline-after: 'always-multi-line'
  value-list-max-empty-lines: 0
  value-no-vendor-prefix: true
