export const BACKEND_REQUEST_META = 'BACKEND_REQUEST_META';
export const BACKEND_REQUEST_META_EXPIRE = 'BACKEND_REQUEST_META_EXPIRE';
export const BACKEND_REQUEST_META_FAILURE = 'BACKEND_REQUEST_META_FAILURE';
export const BACKEND_REQUEST_META_SUCCESS = 'BACKEND_REQUEST_META_SUCCESS';

export const BACKEND_REQUEST_SUCCESS = 'BACKEND_REQUEST_SUCCESS';
export const BACKEND_DERIVED_DATA_SUCCESS = 'BACKEND_DERIVED_DATA_SUCCESS';

export const BACKEND_MULTI_REQUEST_SUCCESS = 'BACKEND_MULTI_REQUEST_SUCCESS';
export const BACKEND_MULTI_REQUEST_META = 'BACKEND_MULTI_REQUEST_META';
export const BACKEND_MULTI_REQUEST_META_SUCCESS = 'BACKEND_MULTI_REQUEST_META_SUCCESS';
export const BACKEND_MULTI_REQUEST_META_EXPIRE = 'BACKEND_MULTI_REQUEST_META_EXPIRE';
export const BACKEND_MULTI_REQUEST_META_FAILURE = 'BACKEND_MULTI_REQUEST_META_FAILURE';
export const BACKEND_MULTI_DERIVED_DATA_SUCCESS = 'BACKEND_MULTI_DERIVED_DATA_SUCCESS';

export const CUSTOMIZATIONS_FAILURE = 'CUSTOMIZATIONS_FAILURE';
export const CUSTOMIZATIONS_REQUEST = 'CUSTOMIZATIONS_REQUEST';
export const CUSTOMIZATIONS_SUCCESS = 'CUSTOMIZATIONS_SUCCESS';

export const CLIENT_USERS_FAILURE = 'CLIENT_USERS_FAILURE';
export const CLIENT_USERS_REQUEST = 'CLIENT_USERS_REQUEST';
export const CLIENT_USERS_SUCCESS = 'CLIENT_USERS_SUCCESS';
