export const DASHBOARD_CPANEL_FILTER_CLEAR = 'DASHBOARD_CPANEL_FILTER_CLEAR';
export const DASHBOARD_CPANEL_FILTER_SEARCH = 'DASHBOARD_CPANEL_FILTER_SEARCH';

export const DASHBOARD_DETAILS_FAILURE = 'DASHBOARD_DETAILS_FAILURE';
export const DASHBOARD_DETAILS_REQUEST = 'DASHBOARD_DETAILS_REQUEST';
export const DASHBOARD_DETAILS_SUCCESS = 'DASHBOARD_DETAILS_SUCCESS';
export const DASHBOARD_SET_SETTINGS = 'DASHBOARD_SET_SETTINGS';

export const DASHBOARD_LAYOUT_CHANGED = 'DASHBOARD_LAYOUT_CHANGED';

export const DASHBOARD_LIST_SUCCESS = 'DASHBOARD_LIST_SUCCESS';

export const DASHBOARD_META_CREATE = 'DASHBOARD_META_CREATE';
export const DASHBOARD_META_REMOVE = 'DASHBOARD_META_REMOVE';

export const DASHBOARD_SET_ACTIVE = 'DASHBOARD_SET_ACTIVE';
export const DASHBOARD_SELECT_COMPONENT = 'DASHBOARD_SELECT_COMPONENT';

export const DASHBOARD_SET_COMPONENT_DATA = 'DASHBOARD_SET_COMPONENT_DATA';
export const DASHBOARD_SET_DATA_SPEC = 'DASHBOARD_SET_DATA_SPEC';
export const DASHBOARD_SET_LAYOUT_DATA = 'DASHBOARD_SET_LAYOUT_DATA';

export const DASHBOARD_SET_SIZE = 'DASHBOARD_SET_SIZE';

export const DASHBOARD_VALUE_MAP_FAILURE = 'DASHBOARD_VALUE_MAP_FAILURE';
export const DASHBOARD_VALUE_MAP_REQUEST = 'DASHBOARD_VALUE_MAP_REQUEST';
export const DASHBOARD_VALUE_MAP_SUCCESS = 'DASHBOARD_VALUE_MAP_SUCCESS';

export const DASHBOARD_UPDATE_VALUE_HASH_TO_REQUEST_HASH_MAP =
    'DASHBOARD_UPDATE_VALUE_HASH_TO_REQUEST_HASH_MAP';

export const DASHBOARD_UPDATE = 'DASHBOARD_UPDATE';
export const DASHBOARD_SETTINGS_UPDATE = 'DASHBOARD_SETTINGS_UPDATE';

export const DASHBOARD_DELETE_SHARE = 'DASHBOARD_DELETE_SHARE';
export const DASHBOARD_CREATE_SHARE = 'DASHBOARD_CREATE_SHARE';

export const DASHOARD_SET_DATA_SPEC_FILLERS = 'DASHOARD_SET_DATA_SPEC_FILLERS';
export const DASHBOARD_SET_BASE_ENTITIES = 'DASHBOARD_CHANGE_BASE_ENTITY';
